config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#search"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'shops', to: "search#shops"
  get 'shops/:id', to: 'shop#show', as: 'shop'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
require 'net/http'
require_relative '../../lib/hotpepper_client'

class SearchController < ApplicationController

  def search
  end

  def shops
    latitude = params[:latitude].to_f
    longitude = params[:longitude].to_f
    range = params[:range]
    page = params[:page] || 1
    order = params[:order]
    genre = params[:genre]
    budget = params[:budget]


    #debug
    # puts "latitude: #{latitude.inspect}"
    # puts "longitude: #{longitude.inspect}"
    # puts "range: #{range.inspect}"
    # puts "page: #{page.inspect}"
    
    client = HotpepperClient.new(latitude, longitude)
    @shops = client.search_shops(latitude, longitude, range, order, genre, budget)
    if @shops.present?
      @shop_count = @shops.size
    else
      @shop_count = 0
    end

    @latitude = latitude
    @longitude = longitude
    @current_page = page

    case range
    when "1"
      @range = '300m'
    when "2"
      @range = '500m'
    when "3", ""
      @range = '1km'
    when "4"
      @range = '2km'
    when "5"
      @range = '3km'
    end

    case order
    when ""
      @order = '距離順'
    when "4"
      @order = 'オススメ順'
    end

    case genre
    when "G001"
      @genre = '居酒屋'
    when "G002"
      @genre = 'ダイニングバー・バル'
    when "G003"
      @genre = '創作料理'
    when "G004"
      @genre = '和食'
    when "G005"
      @genre = '洋食'
    when "G006"
      @genre = 'イタリアン・フレンチ'
    when "G007"
      @genre = '中華'
    when "G008"
      @genre = '焼肉・ホルモン'
    when "G017"
      @genre = '韓国料理'
    when "G009"
      @genre = 'アジア・エスニック料理'
    when "G010"
      @genre = '各国料理'
    when "G011"
      @genre = 'カラオケ・パーティ'
    when "G012"
      @genre = 'バー・カクテル'
    when "G013"
      @genre = 'ラーメン'
    when "G016"
      @genre = 'お好み焼き・もんじゃ'
    when "G014"
      @genre = 'カフェ・スイーツ'
    when "G015"
      @genre = 'その他グルメ'
    end


    case budget
    when ""
      @budget = '指定なし'
    when "B009"
      @budget = '～500円'
    when "B010"
      @budget = '501円～1,000円'
    when "B011"
      @budget = '1,001円～1,500円'
    when "B001"
      @budget = '1,501円～2,000円'
    when "B002"
      @budget = '2,001円～3,000円'
    when "B003"
      @budget = '3,001円～4,000円'
    when "B008"
      @budget = '4,001円～5,000円'
    when "B004"
      @budget = '5,001円～7,000円'
    when "B005"
      @budget = '7,001円～10,000円'
    when "B006"
      @budget = '10,001円～15,000円'
    when "B012"
      @budget = '15,001円～20,000円'
    when "B013"
      @budget = '20,001円～30,000円'
    when "B014"
      @budget = '30,001円～'
    end


    # Kaminari ページング
    # 取得した店舗数が1店舗のみの場合は例外的に処理する。
    # 取得した店舗数が1店舗のみだと配列としてではなく単一のオブジェクトとして値が返ってくるため、同様に処理するとエラーが発生する。
    if @shops.size > 0
      if @shops.is_a?(Array)
        if @shops.size <= 10
          @shops = Kaminari.paginate_array(@shops).page(page)
        else
          @shops = Kaminari.paginate_array(@shops).page(page).per(10)
        end
      else
        @shop_count = 1
        @shops = Kaminari.paginate_array([@shops]).page(page)
      end
    end

    respond_to do |format|
      format.html # クライアントがHTMLを要求した場合、上記で作成したビューを表示
      format.json { render json: @shops } # クライアントがJSONを要求した場合は、JSON形式でデータを返す
    end
  end
end

app/controllers/shop_controller.rb
require 'net/http'
require_relative '../../lib/hotpepper_client'

class ShopController < ApplicationController
  def show
    shop_id = params[:id]

    client = HotpepperClient.new(0,0)
    @shop = client.get_shop(shop_id)

    puts @shop.inspect

    respond_to do |format|
      format.html # クライアントがHTMLを要求した場合、上記で作成したビューを表示
      format.json { render json: @shops } # クライアントがJSONを要求した場合は、JSON形式でデータを返す
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>さがしてmeal</title>
  </head>
  <body>
    <header>
      <font size="1">現在地周辺の飲食店を検索します♪</font>
      <h1 style="font-family: cursive, sans-serif;"><%= image_tag('hedder_logo.png', alt: '!', size: '30x30') %> さがしてmeal <%= image_tag('hedder_logo.png', alt: '!', size: '30x30') %></h1>
    </header>
    
    <main>
      <%= yield %>
    </main>
    
    <footer>
      <a href="https://webservice.recruit.co.jp/"><img src="https://webservice.recruit.co.jp/banner/hotpepper-s.gif" alt="ホットペッパー Webサービス" width="135" height="17" title="ホットペッパー Webサービス"></a>
      <font size="1">【画像提供：ホットペッパー グルメ】</font>
    </footer>
  </body>
</html>

app/views/search/search.html.erb
<h1>Search#search</h1>

app/views/search/shops.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="center-align">
  <form name="range-form">
    <label for="ranges" class="ranges-label">検索範囲</label>
    <select id="ranges" class="ranges-label">
      <option value="3">---</option>
      <option value="1">300m</option>
      <option value="2">500m</option>
      <option value="3">1km </option>
      <option value="4">2km </option>
      <option value="5">3km </option>
    </select>
  </form>
  <font size="1">※範囲を指定しない場合は自動で1kmを指定します。</font>

  <form name="genre-form">
    <label for="genres" class="genres-label">ジャンル</label>
    <select id="genres" class="genres-label">
      <option value="">---</option>
      <option value="G001">居酒屋</option>
      <option value="G002">ダイニングバー・バル</option>
      <option value="G003">創作料理</option>
      <option value="G004">和食</option>
      <option value="G005">洋食</option>
      <option value="G006">イタリアン・フレンチ</option>
      <option value="G007">中華</option>
      <option value="G008">焼肉・ホルモン</option>
      <option value="G017">韓国料理</option>
      <option value="G009">アジア・エスニック料理</option>
      <option value="G010">各国料理</option>
      <option value="G011">カラオケ・パーティ</option>
      <option value="G012">バー・カクテル</option>
      <option value="G013">ラーメン</option>
      <option value="G016">お好み焼き・もんじゃ</option>
      <option value="G014">カフェ・スイーツ</option>
      <option value="G015">その他グルメ</option>
    </select>
  </form>

  <form name="budget-form">
    <label for="budgets" class="budgets-label">ディナー予算</label>
      <select id="budgets" class="budgets-label">
      <option value="">---</option>
      <option value="B009">～500円</option>
      <option value="B010">501円～1,000円</option>
      <option value="B011">1,001円～1,500円</option>
      <option value="B001">1,501円～2,000円</option>
      <option value="B002">2,001円～3,000円</option>
      <option value="B003">3,001円～4,000円</option>
      <option value="B008">4,001円～5,000円</option>
      <option value="B004">5,001円～7,000円</option>
      <option value="B005">7,001円～10,000円</option>
      <option value="B006">10,001円～15,000円</option>
      <option value="B012">15,001円～20,000円</option>
      <option value="B013">20,001円～30,000円</option>
      <option value="B014">30,001円～</option>
    </select>
  </form>

  <form name="order-form">
    <label for="orders" class="orders-label">並べ替え</label>
    <select id="orders" class="orders-label">
      <option value="">距離順</option>
      <option value="4">おススメ順</option>
    </select>
  </form>
  <br><br>

  <form id="location-form" action="/shops" method="GET">
    <input type="hidden" name="latitude" id="latitude" value="">
    <input type="hidden" name="longitude" id="longitude" value="">
    <input type="hidden" name="range" id="range" value="">
    <input type="hidden" name="order" id="order" value="">
    <input type="hidden" name="genre" id="genre" value="">
    <input type="hidden" name="budget" id="budget" value="">
    <button id="search-button" type="button">検索</button>
  </form>

  <% if @shops.any? %>
    <br>
    <font size="1">検索条件... &emsp; 検索範囲：<%= @range %>以内 &emsp; ジャンル：<%= @genre %> &emsp; ディナー予算：<%= @budget %> &emsp; 並べ替え：<%= @order %> </font>
    <% if @shop_count >= 100 %>
      <h3>100件以上の飲食店が見つかりました。</h3>
    <% else %>
      <h3><%= @shop_count %>件のお店が見つかりました。</h3>
    <% end %>
  <% else %>
    <% if @latitude != 0 %>
    <h3>検索条件に合う飲食店が見つかりませんでした。</h3>
    <% end %>
  <% end %>
</div>

<!-- 現在地を取得するJavaScript -->
<script>
navigator.geolocation.getCurrentPosition(function(position) {
  // 緯度・経度を取得
  var latitude = position.coords.latitude;
  var longitude = position.coords.longitude;
  console.log(latitude, longitude);

  // フォームに緯度・経度を設定してsubmit
  var form = document.getElementById('location-form');
  form.querySelector('#latitude').value = latitude;
  form.querySelector('#longitude').value = longitude;
});

// submitボタンがクリックされたときにフォームをsubmitする
document.getElementById('search-button').addEventListener('click', function() {
  var form = document.getElementById('location-form');
  var range = document.getElementById('ranges').value;
  form.querySelector('#range').value = range; // 値をフォームに設定
  var order = document.getElementById('orders').value;
  form.querySelector('#order').value = order; 
  var genre = document.getElementById('genres').value;
  form.querySelector('#genre').value = genre; 
  var budget = document.getElementById('budgets').value;
  form.querySelector('#budget').value = budget; 
  form.submit();
});
</script>

<div id="shop-container">
  <% @shops.each do |shop| %>
    <div class="shop-container">
      <div class="shop-image">
      <% if shop["logo_image"] != "https://imgfp.hotp.jp/SYS/cmn/images/common/diary/custom/m30_img_noimage.gif" %>
        <a href="<%= shop_path(shop["id"]) %>"><img src="<%= shop["logo_image"] %>" alt="<%= shop["name"] %>"></a>
      <% else %>
        <a href="<%= shop_path(shop["id"]) %>"><img src="<%= shop["photo"]["pc"]["l"] %>" alt="<%= shop["name"] %>"></a>
      <% end %>
        <font size="1"></font>
      </div>
      <div class="shop-info">
        <p><%= shop["genre"]["name"] %> &emsp; | &emsp; <%= shop["genre"]["catch"] %></p>
        <a href="<%= shop_path(shop["id"]) %>"><h2 class="shop-name"><%= shop["name"] %></h2></a> 
        <p>営業時間：<%= shop["open"] %></p>
        <p><%= shop["address"] %></p>
        <p>最寄り駅：<%= shop["station_name"] %> &emsp; <%= shop['access'] %></p>
      </div>
    </div>
  <% end %>
</div>

<% if @shops.any? %>
  <div class="center-align">
    <%= paginate @shops, params: { latitude: @latitude, longitude: @longitude} %>
  </div>
<% end %>

<% if @latitude != 0 %>
  <font size="1">現在地 : <%= @latitude %> . <%= @longitude %></font>
<% end %>

app/views/shop/show.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= link_to "戻る", shops_path %>

<div class="center-align">

  <p><%= @shop["large_area"]["name"] %> > <%= @shop["middle_area"]["name"] %> > <%= @shop["small_area"]["name"] %></p>
  <p><%= @shop["genre"]["name"] %> <%= @shop["genre"]["catch"] %></p>
  <table class="center-align">
    <tr>
      <% if @shop["logo_image"] != "https://imgfp.hotp.jp/SYS/cmn/images/common/diary/custom/m30_img_noimage.gif" %>
        <td><img src="<%= @shop["logo_image"] %>" alt="logo"></td>
      <% end %>
      <td><h2 class="show_shop-name"><%= @shop["name"] %></h2></td>
    </tr>
  </table>
  
  <img src="<%= @shop["photo"]["pc"]["l"] %>" alt="photo">

  <h4>店舗情報</h4>
  <table class="table">
    <tr>
      <td>店舗名</td>
      <td><%= @shop["name"] %></td>
    </tr>
    <tr>
      <td>店舗名かな</td>
      <td><%= @shop["name_kana"] %></td>
    </tr>
    <tr>
      <td>URL</td>
      <td><a href= <%@shop["urls"]["pc"] %>><%= @shop["urls"]["pc"] %></a></td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= @shop["genre"]["name"] %></td>
    </tr>
  </table>

  <h4>営業</h4>
  <table class="table">
    <tr>
      <td>営業時間</td>
      <td><%= @shop["open"] %></td>
    </tr>
    <tr>
      <td>定休日</td>
      <td><%= @shop["close"] %></td>
    </tr>
  </table>

  <h4>アクセス</h4>
  <table class="table">
    <tr>
      <td>店舗所在地</td>
      <td><%= @shop["address"] %></td>
    </tr>
    <tr>
      <td>最寄り駅</td>
      <td><%= @shop["station_name"] %></td>
    </tr>
    </tr>
      <td>アクセス</td>
      <td><%= @shop["access"] %></td>
    </tr>
  </table>

  <h4>予算</h4>
  <table class="table">
    <tr>
    <td>平均ディナー予算</td>
      <td><%= @shop["budget"]["average"] %></td>
    </tr>
    <tr>
      <td>カード</td>
      <td><%= @shop["card"]%></td>
    </tr>
    <tr>
      <td>料金備考</td>
      <td><%= @shop["budget_memo"]%></td>
    </tr> 
  </table>

  <h4>お席</h4>
  <table class="table">
    <tr>
      <td>総席数</td>
      <td><%= @shop["capacity"] %></td>
    </tr>
    <tr>
      <td>最大宴会収容人数</td>
      <td><%= @shop["party_capacity"] %></td>
    </tr>
    <tr>
      <td>座敷</td>
      <td><%= @shop["tatami"] %></td>
    </tr>
    <tr>
      <td>掘りごたつ</td>
      <td><%= @shop["horigotatsu"] %></td>
    </tr>
    <tr>
      <td>貸切</td>
      <td><%= @shop["charter"] %></td>
    </tr>
  </table>

  <h4>設備</h4>
  <table class="table">
    <tr>
      <td>Wi-Fi</td>
      <td><%= @shop["wifi"] %></td>
    </tr>
    <tr>
      <td>バリアフリー</td>
      <td><%= @shop["barrier_free"] %></td>
    </tr>
    <tr>
      <td>駐車場</td>
      <td><%= @shop["parking"] %></td>
    </tr>
    <tr>
      <td>禁煙席</td>
      <td><%= @shop["non_smoking"] %></td>
    </tr>
    <tr>
      <td>その他設備</td>
      <td><%= @shop["other_memo"] %></td>
    </tr>
  </table>

  <h4>その他</h4>
  <table class="table">
    <tr>
      <td>飲み放題</td>
      <td><%= @shop["free_drink"] %></td>
    </tr>
    <tr>
      <td>食べ放題</td>
      <td><%= @shop["free_food"] %></td>
    </tr>
    <tr>
      <td>コース料理</td>
      <td><%= @shop["course"] %></td>
    </tr>
    <tr>
      <td>ランチメニュー</td>
      <td><%= @shop["lunch"] %></td>
    </tr>
    <tr>
      <td>英語メニュー</td>
      <td><%= @shop["english"] %></td>
    </tr>
    <tr>
      <td>ペット</td>
      <td><%= @shop["pet"] %></td>
    </tr>
    <tr>
      <td>お子様連れ</td>
      <td><%= @shop["child"] %></td>
    </tr>
    <tr>
      <td>23時以降の営業</td>
      <td><%= @shop["midnight"] %></td>
    </tr>
    <tr>
      <td>クーポン</td>
      <td><a href= <%@shop["coupon_urls"]["pc"] %>><%= @shop["coupon_urls"]["pc"] %></a></td>
    </tr>
  </table>

</div>